#############################################################################
# Makefile for building: MorgageCalculator
# Generated by qmake (3.0) (Qt 5.6.0)
# Project:  MorgageCalculator.pro
# Template: app
# Command: /opt/Qt/bin/qmake -o Makefile MorgageCalculator.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/Qt/include -I/opt/Qt/include/QtWidgets -I/opt/Qt/include/QtGui -I/opt/Qt/include/QtCore -I. -I. -I/opt/Qt/mkspecs/linux-g++
QMAKE         = /opt/Qt/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = MorgageCalculator1.0.0
DISTDIR = /home/mhtrinh/morgage/MorgageCalculator/.tmp/MorgageCalculator1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-z,origin -Wl,-rpath,\$$ORIGIN -Wl,-rpath,/opt/Qt/lib
LIBS          = $(SUBLIBS) -L/opt/Qt/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		MorgageCalculator.cpp \
		MainDialog.cpp moc_MorgageCalculator.cpp \
		moc_MainDialog.cpp
OBJECTS       = main.o \
		MorgageCalculator.o \
		MainDialog.o \
		moc_MorgageCalculator.o \
		moc_MainDialog.o
DIST          = /opt/Qt/mkspecs/features/spec_pre.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/mkspecs/qconfig.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/mkspecs/features/qt_functions.prf \
		/opt/Qt/mkspecs/features/qt_config.prf \
		/opt/Qt/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/mkspecs/features/spec_post.prf \
		/opt/Qt/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/mkspecs/features/default_pre.prf \
		/opt/Qt/mkspecs/features/resolve_config.prf \
		/opt/Qt/mkspecs/features/default_post.prf \
		/opt/Qt/mkspecs/features/warn_on.prf \
		/opt/Qt/mkspecs/features/qt.prf \
		/opt/Qt/mkspecs/features/resources.prf \
		/opt/Qt/mkspecs/features/moc.prf \
		/opt/Qt/mkspecs/features/unix/opengl.prf \
		/opt/Qt/mkspecs/features/uic.prf \
		/opt/Qt/mkspecs/features/unix/thread.prf \
		/opt/Qt/mkspecs/features/testcase_targets.prf \
		/opt/Qt/mkspecs/features/exceptions.prf \
		/opt/Qt/mkspecs/features/yacc.prf \
		/opt/Qt/mkspecs/features/lex.prf \
		MorgageCalculator.pro MorgageCalculator.h \
		MainDialog.h main.cpp \
		MorgageCalculator.cpp \
		MainDialog.cpp
QMAKE_TARGET  = MorgageCalculator
DESTDIR       = 
TARGET        = MorgageCalculator


first: all
####### Build rules

$(TARGET): ui_MorgageCalculator.h ui_MainDialog.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MorgageCalculator.pro /opt/Qt/mkspecs/linux-g++/qmake.conf /opt/Qt/mkspecs/features/spec_pre.prf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf \
		/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/Qt/mkspecs/qconfig.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3drender.pri \
		/opt/Qt/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/Qt/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/Qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_core.pri \
		/opt/Qt/mkspecs/modules/qt_lib_core_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_dbus.pri \
		/opt/Qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_designer.pri \
		/opt/Qt/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_gui.pri \
		/opt/Qt/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_help.pri \
		/opt/Qt/mkspecs/modules/qt_lib_help_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_location.pri \
		/opt/Qt/mkspecs/modules/qt_lib_location_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/Qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_network.pri \
		/opt/Qt/mkspecs/modules/qt_lib_network_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_nfc.pri \
		/opt/Qt/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_opengl.pri \
		/opt/Qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/Qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_positioning.pri \
		/opt/Qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/Qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qml.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quick.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_script.pri \
		/opt/Qt/mkspecs/modules/qt_lib_script_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/Qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_sensors.pri \
		/opt/Qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/Qt/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_serialport.pri \
		/opt/Qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_sql.pri \
		/opt/Qt/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_svg.pri \
		/opt/Qt/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_testlib.pri \
		/opt/Qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/Qt/mkspecs/modules/qt_lib_uitools.pri \
		/opt/Qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webengine.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_websockets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webview.pri \
		/opt/Qt/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_widgets.pri \
		/opt/Qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/Qt/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xml.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/Qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/Qt/mkspecs/features/qt_functions.prf \
		/opt/Qt/mkspecs/features/qt_config.prf \
		/opt/Qt/mkspecs/linux-g++/qmake.conf \
		/opt/Qt/mkspecs/features/spec_post.prf \
		/opt/Qt/mkspecs/features/exclusive_builds.prf \
		/opt/Qt/mkspecs/features/default_pre.prf \
		/opt/Qt/mkspecs/features/resolve_config.prf \
		/opt/Qt/mkspecs/features/default_post.prf \
		/opt/Qt/mkspecs/features/warn_on.prf \
		/opt/Qt/mkspecs/features/qt.prf \
		/opt/Qt/mkspecs/features/resources.prf \
		/opt/Qt/mkspecs/features/moc.prf \
		/opt/Qt/mkspecs/features/unix/opengl.prf \
		/opt/Qt/mkspecs/features/uic.prf \
		/opt/Qt/mkspecs/features/unix/thread.prf \
		/opt/Qt/mkspecs/features/testcase_targets.prf \
		/opt/Qt/mkspecs/features/exceptions.prf \
		/opt/Qt/mkspecs/features/yacc.prf \
		/opt/Qt/mkspecs/features/lex.prf \
		MorgageCalculator.pro \
		/opt/Qt/lib/libQt5Widgets.prl \
		/opt/Qt/lib/libQt5Gui.prl \
		/opt/Qt/lib/libQt5Core.prl
	$(QMAKE) -o Makefile MorgageCalculator.pro
/opt/Qt/mkspecs/features/spec_pre.prf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/unix.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/linux.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/sanitize.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-base.conf:
/opt/Qt5.6.0/5.6/gcc_64/mkspecs/common/g++-unix.conf:
/opt/Qt/mkspecs/qconfig.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dcore.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dinput.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dquick.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/Qt/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_3drender.pri:
/opt/Qt/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/Qt/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_concurrent.pri:
/opt/Qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_core.pri:
/opt/Qt/mkspecs/modules/qt_lib_core_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_dbus.pri:
/opt/Qt/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_designer.pri:
/opt/Qt/mkspecs/modules/qt_lib_designer_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_gui.pri:
/opt/Qt/mkspecs/modules/qt_lib_gui_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_help.pri:
/opt/Qt/mkspecs/modules/qt_lib_help_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_labscontrols_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_labstemplates_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_location.pri:
/opt/Qt/mkspecs/modules/qt_lib_location_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_multimedia.pri:
/opt/Qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/Qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_network.pri:
/opt/Qt/mkspecs/modules/qt_lib_network_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_nfc.pri:
/opt/Qt/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_opengl.pri:
/opt/Qt/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/Qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_positioning.pri:
/opt/Qt/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_printsupport.pri:
/opt/Qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_qml.pri:
/opt/Qt/mkspecs/modules/qt_lib_qml_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_qmltest.pri:
/opt/Qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_quick.pri:
/opt/Qt/mkspecs/modules/qt_lib_quick_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/Qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_script.pri:
/opt/Qt/mkspecs/modules/qt_lib_script_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_scripttools.pri:
/opt/Qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_sensors.pri:
/opt/Qt/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_serialbus.pri:
/opt/Qt/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_serialport.pri:
/opt/Qt/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_sql.pri:
/opt/Qt/mkspecs/modules/qt_lib_sql_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_svg.pri:
/opt/Qt/mkspecs/modules/qt_lib_svg_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_testlib.pri:
/opt/Qt/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/Qt/mkspecs/modules/qt_lib_uitools.pri:
/opt/Qt/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_webchannel.pri:
/opt/Qt/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_webengine.pri:
/opt/Qt/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/Qt/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/Qt/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_websockets.pri:
/opt/Qt/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_webview.pri:
/opt/Qt/mkspecs/modules/qt_lib_webview_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_widgets.pri:
/opt/Qt/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_x11extras.pri:
/opt/Qt/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_xml.pri:
/opt/Qt/mkspecs/modules/qt_lib_xml_private.pri:
/opt/Qt/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/Qt/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/Qt/mkspecs/features/qt_functions.prf:
/opt/Qt/mkspecs/features/qt_config.prf:
/opt/Qt/mkspecs/linux-g++/qmake.conf:
/opt/Qt/mkspecs/features/spec_post.prf:
/opt/Qt/mkspecs/features/exclusive_builds.prf:
/opt/Qt/mkspecs/features/default_pre.prf:
/opt/Qt/mkspecs/features/resolve_config.prf:
/opt/Qt/mkspecs/features/default_post.prf:
/opt/Qt/mkspecs/features/warn_on.prf:
/opt/Qt/mkspecs/features/qt.prf:
/opt/Qt/mkspecs/features/resources.prf:
/opt/Qt/mkspecs/features/moc.prf:
/opt/Qt/mkspecs/features/unix/opengl.prf:
/opt/Qt/mkspecs/features/uic.prf:
/opt/Qt/mkspecs/features/unix/thread.prf:
/opt/Qt/mkspecs/features/testcase_targets.prf:
/opt/Qt/mkspecs/features/exceptions.prf:
/opt/Qt/mkspecs/features/yacc.prf:
/opt/Qt/mkspecs/features/lex.prf:
MorgageCalculator.pro:
/opt/Qt/lib/libQt5Widgets.prl:
/opt/Qt/lib/libQt5Gui.prl:
/opt/Qt/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile MorgageCalculator.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents MorgageCalculator.h MainDialog.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp MorgageCalculator.cpp MainDialog.cpp $(DISTDIR)/
	$(COPY_FILE) --parents MorgageCalculator.ui MainDialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_header_make_all: moc_MorgageCalculator.cpp moc_MainDialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MorgageCalculator.cpp moc_MainDialog.cpp
moc_MorgageCalculator.cpp: /opt/Qt/include/QtWidgets/QWidget \
		/opt/Qt/include/QtWidgets/qwidget.h \
		/opt/Qt/include/QtGui/qwindowdefs.h \
		/opt/Qt/include/QtCore/qglobal.h \
		/opt/Qt/include/QtCore/qconfig.h \
		/opt/Qt/include/QtCore/qfeatures.h \
		/opt/Qt/include/QtCore/qsystemdetection.h \
		/opt/Qt/include/QtCore/qprocessordetection.h \
		/opt/Qt/include/QtCore/qcompilerdetection.h \
		/opt/Qt/include/QtCore/qtypeinfo.h \
		/opt/Qt/include/QtCore/qtypetraits.h \
		/opt/Qt/include/QtCore/qisenum.h \
		/opt/Qt/include/QtCore/qsysinfo.h \
		/opt/Qt/include/QtCore/qlogging.h \
		/opt/Qt/include/QtCore/qflags.h \
		/opt/Qt/include/QtCore/qatomic.h \
		/opt/Qt/include/QtCore/qbasicatomic.h \
		/opt/Qt/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/include/QtCore/qgenericatomic.h \
		/opt/Qt/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/include/QtCore/qatomic_gcc.h \
		/opt/Qt/include/QtCore/qatomic_msvc.h \
		/opt/Qt/include/QtCore/qatomic_armv7.h \
		/opt/Qt/include/QtCore/qatomic_armv6.h \
		/opt/Qt/include/QtCore/qatomic_armv5.h \
		/opt/Qt/include/QtCore/qatomic_ia64.h \
		/opt/Qt/include/QtCore/qatomic_x86.h \
		/opt/Qt/include/QtCore/qatomic_unix.h \
		/opt/Qt/include/QtCore/qglobalstatic.h \
		/opt/Qt/include/QtCore/qmutex.h \
		/opt/Qt/include/QtCore/qnumeric.h \
		/opt/Qt/include/QtCore/qversiontagging.h \
		/opt/Qt/include/QtCore/qobjectdefs.h \
		/opt/Qt/include/QtCore/qnamespace.h \
		/opt/Qt/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/include/QtCore/qobject.h \
		/opt/Qt/include/QtCore/qstring.h \
		/opt/Qt/include/QtCore/qchar.h \
		/opt/Qt/include/QtCore/qbytearray.h \
		/opt/Qt/include/QtCore/qrefcount.h \
		/opt/Qt/include/QtCore/qarraydata.h \
		/opt/Qt/include/QtCore/qstringbuilder.h \
		/opt/Qt/include/QtCore/qlist.h \
		/opt/Qt/include/QtCore/qalgorithms.h \
		/opt/Qt/include/QtCore/qiterator.h \
		/opt/Qt/include/QtCore/qhashfunctions.h \
		/opt/Qt/include/QtCore/qpair.h \
		/opt/Qt/include/QtCore/qbytearraylist.h \
		/opt/Qt/include/QtCore/qstringlist.h \
		/opt/Qt/include/QtCore/qregexp.h \
		/opt/Qt/include/QtCore/qstringmatcher.h \
		/opt/Qt/include/QtCore/qcoreevent.h \
		/opt/Qt/include/QtCore/qscopedpointer.h \
		/opt/Qt/include/QtCore/qmetatype.h \
		/opt/Qt/include/QtCore/qvarlengtharray.h \
		/opt/Qt/include/QtCore/qcontainerfwd.h \
		/opt/Qt/include/QtCore/qobject_impl.h \
		/opt/Qt/include/QtCore/qmargins.h \
		/opt/Qt/include/QtGui/qpaintdevice.h \
		/opt/Qt/include/QtCore/qrect.h \
		/opt/Qt/include/QtCore/qsize.h \
		/opt/Qt/include/QtCore/qpoint.h \
		/opt/Qt/include/QtGui/qpalette.h \
		/opt/Qt/include/QtGui/qcolor.h \
		/opt/Qt/include/QtGui/qrgb.h \
		/opt/Qt/include/QtGui/qrgba64.h \
		/opt/Qt/include/QtGui/qbrush.h \
		/opt/Qt/include/QtCore/qvector.h \
		/opt/Qt/include/QtGui/qmatrix.h \
		/opt/Qt/include/QtGui/qpolygon.h \
		/opt/Qt/include/QtGui/qregion.h \
		/opt/Qt/include/QtCore/qdatastream.h \
		/opt/Qt/include/QtCore/qiodevice.h \
		/opt/Qt/include/QtCore/qline.h \
		/opt/Qt/include/QtGui/qtransform.h \
		/opt/Qt/include/QtGui/qpainterpath.h \
		/opt/Qt/include/QtGui/qimage.h \
		/opt/Qt/include/QtGui/qpixelformat.h \
		/opt/Qt/include/QtGui/qpixmap.h \
		/opt/Qt/include/QtCore/qsharedpointer.h \
		/opt/Qt/include/QtCore/qshareddata.h \
		/opt/Qt/include/QtCore/qhash.h \
		/opt/Qt/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/include/QtGui/qfont.h \
		/opt/Qt/include/QtGui/qfontmetrics.h \
		/opt/Qt/include/QtGui/qfontinfo.h \
		/opt/Qt/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/include/QtGui/qcursor.h \
		/opt/Qt/include/QtGui/qkeysequence.h \
		/opt/Qt/include/QtGui/qevent.h \
		/opt/Qt/include/QtCore/qvariant.h \
		/opt/Qt/include/QtCore/qmap.h \
		/opt/Qt/include/QtCore/qdebug.h \
		/opt/Qt/include/QtCore/qtextstream.h \
		/opt/Qt/include/QtCore/qlocale.h \
		/opt/Qt/include/QtCore/qset.h \
		/opt/Qt/include/QtCore/qcontiguouscache.h \
		/opt/Qt/include/QtCore/qurl.h \
		/opt/Qt/include/QtCore/qurlquery.h \
		/opt/Qt/include/QtCore/qfile.h \
		/opt/Qt/include/QtCore/qfiledevice.h \
		/opt/Qt/include/QtGui/qvector2d.h \
		/opt/Qt/include/QtGui/qtouchdevice.h \
		/opt/Qt/include/QtCore/QString \
		MorgageCalculator.h
	/opt/Qt/bin/moc $(DEFINES) -I/opt/Qt/mkspecs/linux-g++ -I/home/mhtrinh/morgage/MorgageCalculator -I/opt/Qt/include -I/opt/Qt/include/QtWidgets -I/opt/Qt/include/QtGui -I/opt/Qt/include/QtCore MorgageCalculator.h -o moc_MorgageCalculator.cpp

moc_MainDialog.cpp: /opt/Qt/include/QtWidgets/QDialog \
		/opt/Qt/include/QtWidgets/qdialog.h \
		/opt/Qt/include/QtWidgets/qwidget.h \
		/opt/Qt/include/QtGui/qwindowdefs.h \
		/opt/Qt/include/QtCore/qglobal.h \
		/opt/Qt/include/QtCore/qconfig.h \
		/opt/Qt/include/QtCore/qfeatures.h \
		/opt/Qt/include/QtCore/qsystemdetection.h \
		/opt/Qt/include/QtCore/qprocessordetection.h \
		/opt/Qt/include/QtCore/qcompilerdetection.h \
		/opt/Qt/include/QtCore/qtypeinfo.h \
		/opt/Qt/include/QtCore/qtypetraits.h \
		/opt/Qt/include/QtCore/qisenum.h \
		/opt/Qt/include/QtCore/qsysinfo.h \
		/opt/Qt/include/QtCore/qlogging.h \
		/opt/Qt/include/QtCore/qflags.h \
		/opt/Qt/include/QtCore/qatomic.h \
		/opt/Qt/include/QtCore/qbasicatomic.h \
		/opt/Qt/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/include/QtCore/qgenericatomic.h \
		/opt/Qt/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/include/QtCore/qatomic_gcc.h \
		/opt/Qt/include/QtCore/qatomic_msvc.h \
		/opt/Qt/include/QtCore/qatomic_armv7.h \
		/opt/Qt/include/QtCore/qatomic_armv6.h \
		/opt/Qt/include/QtCore/qatomic_armv5.h \
		/opt/Qt/include/QtCore/qatomic_ia64.h \
		/opt/Qt/include/QtCore/qatomic_x86.h \
		/opt/Qt/include/QtCore/qatomic_unix.h \
		/opt/Qt/include/QtCore/qglobalstatic.h \
		/opt/Qt/include/QtCore/qmutex.h \
		/opt/Qt/include/QtCore/qnumeric.h \
		/opt/Qt/include/QtCore/qversiontagging.h \
		/opt/Qt/include/QtCore/qobjectdefs.h \
		/opt/Qt/include/QtCore/qnamespace.h \
		/opt/Qt/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/include/QtCore/qobject.h \
		/opt/Qt/include/QtCore/qstring.h \
		/opt/Qt/include/QtCore/qchar.h \
		/opt/Qt/include/QtCore/qbytearray.h \
		/opt/Qt/include/QtCore/qrefcount.h \
		/opt/Qt/include/QtCore/qarraydata.h \
		/opt/Qt/include/QtCore/qstringbuilder.h \
		/opt/Qt/include/QtCore/qlist.h \
		/opt/Qt/include/QtCore/qalgorithms.h \
		/opt/Qt/include/QtCore/qiterator.h \
		/opt/Qt/include/QtCore/qhashfunctions.h \
		/opt/Qt/include/QtCore/qpair.h \
		/opt/Qt/include/QtCore/qbytearraylist.h \
		/opt/Qt/include/QtCore/qstringlist.h \
		/opt/Qt/include/QtCore/qregexp.h \
		/opt/Qt/include/QtCore/qstringmatcher.h \
		/opt/Qt/include/QtCore/qcoreevent.h \
		/opt/Qt/include/QtCore/qscopedpointer.h \
		/opt/Qt/include/QtCore/qmetatype.h \
		/opt/Qt/include/QtCore/qvarlengtharray.h \
		/opt/Qt/include/QtCore/qcontainerfwd.h \
		/opt/Qt/include/QtCore/qobject_impl.h \
		/opt/Qt/include/QtCore/qmargins.h \
		/opt/Qt/include/QtGui/qpaintdevice.h \
		/opt/Qt/include/QtCore/qrect.h \
		/opt/Qt/include/QtCore/qsize.h \
		/opt/Qt/include/QtCore/qpoint.h \
		/opt/Qt/include/QtGui/qpalette.h \
		/opt/Qt/include/QtGui/qcolor.h \
		/opt/Qt/include/QtGui/qrgb.h \
		/opt/Qt/include/QtGui/qrgba64.h \
		/opt/Qt/include/QtGui/qbrush.h \
		/opt/Qt/include/QtCore/qvector.h \
		/opt/Qt/include/QtGui/qmatrix.h \
		/opt/Qt/include/QtGui/qpolygon.h \
		/opt/Qt/include/QtGui/qregion.h \
		/opt/Qt/include/QtCore/qdatastream.h \
		/opt/Qt/include/QtCore/qiodevice.h \
		/opt/Qt/include/QtCore/qline.h \
		/opt/Qt/include/QtGui/qtransform.h \
		/opt/Qt/include/QtGui/qpainterpath.h \
		/opt/Qt/include/QtGui/qimage.h \
		/opt/Qt/include/QtGui/qpixelformat.h \
		/opt/Qt/include/QtGui/qpixmap.h \
		/opt/Qt/include/QtCore/qsharedpointer.h \
		/opt/Qt/include/QtCore/qshareddata.h \
		/opt/Qt/include/QtCore/qhash.h \
		/opt/Qt/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/include/QtGui/qfont.h \
		/opt/Qt/include/QtGui/qfontmetrics.h \
		/opt/Qt/include/QtGui/qfontinfo.h \
		/opt/Qt/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/include/QtGui/qcursor.h \
		/opt/Qt/include/QtGui/qkeysequence.h \
		/opt/Qt/include/QtGui/qevent.h \
		/opt/Qt/include/QtCore/qvariant.h \
		/opt/Qt/include/QtCore/qmap.h \
		/opt/Qt/include/QtCore/qdebug.h \
		/opt/Qt/include/QtCore/qtextstream.h \
		/opt/Qt/include/QtCore/qlocale.h \
		/opt/Qt/include/QtCore/qset.h \
		/opt/Qt/include/QtCore/qcontiguouscache.h \
		/opt/Qt/include/QtCore/qurl.h \
		/opt/Qt/include/QtCore/qurlquery.h \
		/opt/Qt/include/QtCore/qfile.h \
		/opt/Qt/include/QtCore/qfiledevice.h \
		/opt/Qt/include/QtGui/qvector2d.h \
		/opt/Qt/include/QtGui/qtouchdevice.h \
		MainDialog.h
	/opt/Qt/bin/moc $(DEFINES) -I/opt/Qt/mkspecs/linux-g++ -I/home/mhtrinh/morgage/MorgageCalculator -I/opt/Qt/include -I/opt/Qt/include/QtWidgets -I/opt/Qt/include/QtGui -I/opt/Qt/include/QtCore MainDialog.h -o moc_MainDialog.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_MorgageCalculator.h ui_MainDialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_MorgageCalculator.h ui_MainDialog.h
ui_MorgageCalculator.h: MorgageCalculator.ui
	/opt/Qt/bin/uic MorgageCalculator.ui -o ui_MorgageCalculator.h

ui_MainDialog.h: MainDialog.ui
	/opt/Qt/bin/uic MainDialog.ui -o ui_MainDialog.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp MainDialog.h \
		/opt/Qt/include/QtWidgets/QDialog \
		/opt/Qt/include/QtWidgets/qdialog.h \
		/opt/Qt/include/QtWidgets/qwidget.h \
		/opt/Qt/include/QtGui/qwindowdefs.h \
		/opt/Qt/include/QtCore/qglobal.h \
		/opt/Qt/include/QtCore/qconfig.h \
		/opt/Qt/include/QtCore/qfeatures.h \
		/opt/Qt/include/QtCore/qsystemdetection.h \
		/opt/Qt/include/QtCore/qprocessordetection.h \
		/opt/Qt/include/QtCore/qcompilerdetection.h \
		/opt/Qt/include/QtCore/qtypeinfo.h \
		/opt/Qt/include/QtCore/qtypetraits.h \
		/opt/Qt/include/QtCore/qisenum.h \
		/opt/Qt/include/QtCore/qsysinfo.h \
		/opt/Qt/include/QtCore/qlogging.h \
		/opt/Qt/include/QtCore/qflags.h \
		/opt/Qt/include/QtCore/qatomic.h \
		/opt/Qt/include/QtCore/qbasicatomic.h \
		/opt/Qt/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/include/QtCore/qgenericatomic.h \
		/opt/Qt/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/include/QtCore/qatomic_gcc.h \
		/opt/Qt/include/QtCore/qatomic_msvc.h \
		/opt/Qt/include/QtCore/qatomic_armv7.h \
		/opt/Qt/include/QtCore/qatomic_armv6.h \
		/opt/Qt/include/QtCore/qatomic_armv5.h \
		/opt/Qt/include/QtCore/qatomic_ia64.h \
		/opt/Qt/include/QtCore/qatomic_x86.h \
		/opt/Qt/include/QtCore/qatomic_unix.h \
		/opt/Qt/include/QtCore/qglobalstatic.h \
		/opt/Qt/include/QtCore/qmutex.h \
		/opt/Qt/include/QtCore/qnumeric.h \
		/opt/Qt/include/QtCore/qversiontagging.h \
		/opt/Qt/include/QtCore/qobjectdefs.h \
		/opt/Qt/include/QtCore/qnamespace.h \
		/opt/Qt/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/include/QtCore/qobject.h \
		/opt/Qt/include/QtCore/qstring.h \
		/opt/Qt/include/QtCore/qchar.h \
		/opt/Qt/include/QtCore/qbytearray.h \
		/opt/Qt/include/QtCore/qrefcount.h \
		/opt/Qt/include/QtCore/qarraydata.h \
		/opt/Qt/include/QtCore/qstringbuilder.h \
		/opt/Qt/include/QtCore/qlist.h \
		/opt/Qt/include/QtCore/qalgorithms.h \
		/opt/Qt/include/QtCore/qiterator.h \
		/opt/Qt/include/QtCore/qhashfunctions.h \
		/opt/Qt/include/QtCore/qpair.h \
		/opt/Qt/include/QtCore/qbytearraylist.h \
		/opt/Qt/include/QtCore/qstringlist.h \
		/opt/Qt/include/QtCore/qregexp.h \
		/opt/Qt/include/QtCore/qstringmatcher.h \
		/opt/Qt/include/QtCore/qcoreevent.h \
		/opt/Qt/include/QtCore/qscopedpointer.h \
		/opt/Qt/include/QtCore/qmetatype.h \
		/opt/Qt/include/QtCore/qvarlengtharray.h \
		/opt/Qt/include/QtCore/qcontainerfwd.h \
		/opt/Qt/include/QtCore/qobject_impl.h \
		/opt/Qt/include/QtCore/qmargins.h \
		/opt/Qt/include/QtGui/qpaintdevice.h \
		/opt/Qt/include/QtCore/qrect.h \
		/opt/Qt/include/QtCore/qsize.h \
		/opt/Qt/include/QtCore/qpoint.h \
		/opt/Qt/include/QtGui/qpalette.h \
		/opt/Qt/include/QtGui/qcolor.h \
		/opt/Qt/include/QtGui/qrgb.h \
		/opt/Qt/include/QtGui/qrgba64.h \
		/opt/Qt/include/QtGui/qbrush.h \
		/opt/Qt/include/QtCore/qvector.h \
		/opt/Qt/include/QtGui/qmatrix.h \
		/opt/Qt/include/QtGui/qpolygon.h \
		/opt/Qt/include/QtGui/qregion.h \
		/opt/Qt/include/QtCore/qdatastream.h \
		/opt/Qt/include/QtCore/qiodevice.h \
		/opt/Qt/include/QtCore/qline.h \
		/opt/Qt/include/QtGui/qtransform.h \
		/opt/Qt/include/QtGui/qpainterpath.h \
		/opt/Qt/include/QtGui/qimage.h \
		/opt/Qt/include/QtGui/qpixelformat.h \
		/opt/Qt/include/QtGui/qpixmap.h \
		/opt/Qt/include/QtCore/qsharedpointer.h \
		/opt/Qt/include/QtCore/qshareddata.h \
		/opt/Qt/include/QtCore/qhash.h \
		/opt/Qt/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/include/QtGui/qfont.h \
		/opt/Qt/include/QtGui/qfontmetrics.h \
		/opt/Qt/include/QtGui/qfontinfo.h \
		/opt/Qt/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/include/QtGui/qcursor.h \
		/opt/Qt/include/QtGui/qkeysequence.h \
		/opt/Qt/include/QtGui/qevent.h \
		/opt/Qt/include/QtCore/qvariant.h \
		/opt/Qt/include/QtCore/qmap.h \
		/opt/Qt/include/QtCore/qdebug.h \
		/opt/Qt/include/QtCore/qtextstream.h \
		/opt/Qt/include/QtCore/qlocale.h \
		/opt/Qt/include/QtCore/qset.h \
		/opt/Qt/include/QtCore/qcontiguouscache.h \
		/opt/Qt/include/QtCore/qurl.h \
		/opt/Qt/include/QtCore/qurlquery.h \
		/opt/Qt/include/QtCore/qfile.h \
		/opt/Qt/include/QtCore/qfiledevice.h \
		/opt/Qt/include/QtGui/qvector2d.h \
		/opt/Qt/include/QtGui/qtouchdevice.h \
		/opt/Qt/include/QtWidgets/QApplication \
		/opt/Qt/include/QtWidgets/qapplication.h \
		/opt/Qt/include/QtCore/qcoreapplication.h \
		/opt/Qt/include/QtCore/qeventloop.h \
		/opt/Qt/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt/include/QtGui/qguiapplication.h \
		/opt/Qt/include/QtGui/qinputmethod.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

MorgageCalculator.o: MorgageCalculator.cpp MorgageCalculator.h \
		/opt/Qt/include/QtWidgets/QWidget \
		/opt/Qt/include/QtWidgets/qwidget.h \
		/opt/Qt/include/QtGui/qwindowdefs.h \
		/opt/Qt/include/QtCore/qglobal.h \
		/opt/Qt/include/QtCore/qconfig.h \
		/opt/Qt/include/QtCore/qfeatures.h \
		/opt/Qt/include/QtCore/qsystemdetection.h \
		/opt/Qt/include/QtCore/qprocessordetection.h \
		/opt/Qt/include/QtCore/qcompilerdetection.h \
		/opt/Qt/include/QtCore/qtypeinfo.h \
		/opt/Qt/include/QtCore/qtypetraits.h \
		/opt/Qt/include/QtCore/qisenum.h \
		/opt/Qt/include/QtCore/qsysinfo.h \
		/opt/Qt/include/QtCore/qlogging.h \
		/opt/Qt/include/QtCore/qflags.h \
		/opt/Qt/include/QtCore/qatomic.h \
		/opt/Qt/include/QtCore/qbasicatomic.h \
		/opt/Qt/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/include/QtCore/qgenericatomic.h \
		/opt/Qt/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/include/QtCore/qatomic_gcc.h \
		/opt/Qt/include/QtCore/qatomic_msvc.h \
		/opt/Qt/include/QtCore/qatomic_armv7.h \
		/opt/Qt/include/QtCore/qatomic_armv6.h \
		/opt/Qt/include/QtCore/qatomic_armv5.h \
		/opt/Qt/include/QtCore/qatomic_ia64.h \
		/opt/Qt/include/QtCore/qatomic_x86.h \
		/opt/Qt/include/QtCore/qatomic_unix.h \
		/opt/Qt/include/QtCore/qglobalstatic.h \
		/opt/Qt/include/QtCore/qmutex.h \
		/opt/Qt/include/QtCore/qnumeric.h \
		/opt/Qt/include/QtCore/qversiontagging.h \
		/opt/Qt/include/QtCore/qobjectdefs.h \
		/opt/Qt/include/QtCore/qnamespace.h \
		/opt/Qt/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/include/QtCore/qobject.h \
		/opt/Qt/include/QtCore/qstring.h \
		/opt/Qt/include/QtCore/qchar.h \
		/opt/Qt/include/QtCore/qbytearray.h \
		/opt/Qt/include/QtCore/qrefcount.h \
		/opt/Qt/include/QtCore/qarraydata.h \
		/opt/Qt/include/QtCore/qstringbuilder.h \
		/opt/Qt/include/QtCore/qlist.h \
		/opt/Qt/include/QtCore/qalgorithms.h \
		/opt/Qt/include/QtCore/qiterator.h \
		/opt/Qt/include/QtCore/qhashfunctions.h \
		/opt/Qt/include/QtCore/qpair.h \
		/opt/Qt/include/QtCore/qbytearraylist.h \
		/opt/Qt/include/QtCore/qstringlist.h \
		/opt/Qt/include/QtCore/qregexp.h \
		/opt/Qt/include/QtCore/qstringmatcher.h \
		/opt/Qt/include/QtCore/qcoreevent.h \
		/opt/Qt/include/QtCore/qscopedpointer.h \
		/opt/Qt/include/QtCore/qmetatype.h \
		/opt/Qt/include/QtCore/qvarlengtharray.h \
		/opt/Qt/include/QtCore/qcontainerfwd.h \
		/opt/Qt/include/QtCore/qobject_impl.h \
		/opt/Qt/include/QtCore/qmargins.h \
		/opt/Qt/include/QtGui/qpaintdevice.h \
		/opt/Qt/include/QtCore/qrect.h \
		/opt/Qt/include/QtCore/qsize.h \
		/opt/Qt/include/QtCore/qpoint.h \
		/opt/Qt/include/QtGui/qpalette.h \
		/opt/Qt/include/QtGui/qcolor.h \
		/opt/Qt/include/QtGui/qrgb.h \
		/opt/Qt/include/QtGui/qrgba64.h \
		/opt/Qt/include/QtGui/qbrush.h \
		/opt/Qt/include/QtCore/qvector.h \
		/opt/Qt/include/QtGui/qmatrix.h \
		/opt/Qt/include/QtGui/qpolygon.h \
		/opt/Qt/include/QtGui/qregion.h \
		/opt/Qt/include/QtCore/qdatastream.h \
		/opt/Qt/include/QtCore/qiodevice.h \
		/opt/Qt/include/QtCore/qline.h \
		/opt/Qt/include/QtGui/qtransform.h \
		/opt/Qt/include/QtGui/qpainterpath.h \
		/opt/Qt/include/QtGui/qimage.h \
		/opt/Qt/include/QtGui/qpixelformat.h \
		/opt/Qt/include/QtGui/qpixmap.h \
		/opt/Qt/include/QtCore/qsharedpointer.h \
		/opt/Qt/include/QtCore/qshareddata.h \
		/opt/Qt/include/QtCore/qhash.h \
		/opt/Qt/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/include/QtGui/qfont.h \
		/opt/Qt/include/QtGui/qfontmetrics.h \
		/opt/Qt/include/QtGui/qfontinfo.h \
		/opt/Qt/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/include/QtGui/qcursor.h \
		/opt/Qt/include/QtGui/qkeysequence.h \
		/opt/Qt/include/QtGui/qevent.h \
		/opt/Qt/include/QtCore/qvariant.h \
		/opt/Qt/include/QtCore/qmap.h \
		/opt/Qt/include/QtCore/qdebug.h \
		/opt/Qt/include/QtCore/qtextstream.h \
		/opt/Qt/include/QtCore/qlocale.h \
		/opt/Qt/include/QtCore/qset.h \
		/opt/Qt/include/QtCore/qcontiguouscache.h \
		/opt/Qt/include/QtCore/qurl.h \
		/opt/Qt/include/QtCore/qurlquery.h \
		/opt/Qt/include/QtCore/qfile.h \
		/opt/Qt/include/QtCore/qfiledevice.h \
		/opt/Qt/include/QtGui/qvector2d.h \
		/opt/Qt/include/QtGui/qtouchdevice.h \
		/opt/Qt/include/QtCore/QString \
		ui_MorgageCalculator.h \
		/opt/Qt/include/QtCore/QVariant \
		/opt/Qt/include/QtWidgets/QAction \
		/opt/Qt/include/QtWidgets/qaction.h \
		/opt/Qt/include/QtGui/qicon.h \
		/opt/Qt/include/QtWidgets/qactiongroup.h \
		/opt/Qt/include/QtWidgets/QApplication \
		/opt/Qt/include/QtWidgets/qapplication.h \
		/opt/Qt/include/QtCore/qcoreapplication.h \
		/opt/Qt/include/QtCore/qeventloop.h \
		/opt/Qt/include/QtWidgets/qdesktopwidget.h \
		/opt/Qt/include/QtGui/qguiapplication.h \
		/opt/Qt/include/QtGui/qinputmethod.h \
		/opt/Qt/include/QtWidgets/QButtonGroup \
		/opt/Qt/include/QtWidgets/qbuttongroup.h \
		/opt/Qt/include/QtWidgets/QFormLayout \
		/opt/Qt/include/QtWidgets/qformlayout.h \
		/opt/Qt/include/QtWidgets/QLayout \
		/opt/Qt/include/QtWidgets/qlayout.h \
		/opt/Qt/include/QtWidgets/qlayoutitem.h \
		/opt/Qt/include/QtWidgets/qboxlayout.h \
		/opt/Qt/include/QtWidgets/qgridlayout.h \
		/opt/Qt/include/QtWidgets/QGridLayout \
		/opt/Qt/include/QtWidgets/QGroupBox \
		/opt/Qt/include/QtWidgets/qgroupbox.h \
		/opt/Qt/include/QtWidgets/qframe.h \
		/opt/Qt/include/QtWidgets/QHeaderView \
		/opt/Qt/include/QtWidgets/qheaderview.h \
		/opt/Qt/include/QtWidgets/qabstractitemview.h \
		/opt/Qt/include/QtWidgets/qabstractscrollarea.h \
		/opt/Qt/include/QtCore/qabstractitemmodel.h \
		/opt/Qt/include/QtCore/qitemselectionmodel.h \
		/opt/Qt/include/QtWidgets/qabstractitemdelegate.h \
		/opt/Qt/include/QtWidgets/qstyleoption.h \
		/opt/Qt/include/QtWidgets/qabstractspinbox.h \
		/opt/Qt/include/QtGui/qvalidator.h \
		/opt/Qt/include/QtCore/qregularexpression.h \
		/opt/Qt/include/QtWidgets/qslider.h \
		/opt/Qt/include/QtWidgets/qabstractslider.h \
		/opt/Qt/include/QtWidgets/qstyle.h \
		/opt/Qt/include/QtWidgets/qtabbar.h \
		/opt/Qt/include/QtWidgets/qtabwidget.h \
		/opt/Qt/include/QtWidgets/qrubberband.h \
		/opt/Qt/include/QtWidgets/QLabel \
		/opt/Qt/include/QtWidgets/qlabel.h \
		/opt/Qt/include/QtWidgets/QLineEdit \
		/opt/Qt/include/QtWidgets/qlineedit.h \
		/opt/Qt/include/QtGui/qtextcursor.h \
		/opt/Qt/include/QtGui/qtextformat.h \
		/opt/Qt/include/QtGui/qpen.h \
		/opt/Qt/include/QtGui/qtextoption.h \
		/opt/Qt/include/QtWidgets/QRadioButton \
		/opt/Qt/include/QtWidgets/qradiobutton.h \
		/opt/Qt/include/QtWidgets/qabstractbutton.h \
		/opt/Qt/include/QtWidgets/QSpacerItem \
		/opt/Qt/include/QtWidgets/QVBoxLayout
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MorgageCalculator.o MorgageCalculator.cpp

MainDialog.o: MainDialog.cpp MainDialog.h \
		/opt/Qt/include/QtWidgets/QDialog \
		/opt/Qt/include/QtWidgets/qdialog.h \
		/opt/Qt/include/QtWidgets/qwidget.h \
		/opt/Qt/include/QtGui/qwindowdefs.h \
		/opt/Qt/include/QtCore/qglobal.h \
		/opt/Qt/include/QtCore/qconfig.h \
		/opt/Qt/include/QtCore/qfeatures.h \
		/opt/Qt/include/QtCore/qsystemdetection.h \
		/opt/Qt/include/QtCore/qprocessordetection.h \
		/opt/Qt/include/QtCore/qcompilerdetection.h \
		/opt/Qt/include/QtCore/qtypeinfo.h \
		/opt/Qt/include/QtCore/qtypetraits.h \
		/opt/Qt/include/QtCore/qisenum.h \
		/opt/Qt/include/QtCore/qsysinfo.h \
		/opt/Qt/include/QtCore/qlogging.h \
		/opt/Qt/include/QtCore/qflags.h \
		/opt/Qt/include/QtCore/qatomic.h \
		/opt/Qt/include/QtCore/qbasicatomic.h \
		/opt/Qt/include/QtCore/qatomic_bootstrap.h \
		/opt/Qt/include/QtCore/qgenericatomic.h \
		/opt/Qt/include/QtCore/qatomic_cxx11.h \
		/opt/Qt/include/QtCore/qatomic_gcc.h \
		/opt/Qt/include/QtCore/qatomic_msvc.h \
		/opt/Qt/include/QtCore/qatomic_armv7.h \
		/opt/Qt/include/QtCore/qatomic_armv6.h \
		/opt/Qt/include/QtCore/qatomic_armv5.h \
		/opt/Qt/include/QtCore/qatomic_ia64.h \
		/opt/Qt/include/QtCore/qatomic_x86.h \
		/opt/Qt/include/QtCore/qatomic_unix.h \
		/opt/Qt/include/QtCore/qglobalstatic.h \
		/opt/Qt/include/QtCore/qmutex.h \
		/opt/Qt/include/QtCore/qnumeric.h \
		/opt/Qt/include/QtCore/qversiontagging.h \
		/opt/Qt/include/QtCore/qobjectdefs.h \
		/opt/Qt/include/QtCore/qnamespace.h \
		/opt/Qt/include/QtCore/qobjectdefs_impl.h \
		/opt/Qt/include/QtGui/qwindowdefs_win.h \
		/opt/Qt/include/QtCore/qobject.h \
		/opt/Qt/include/QtCore/qstring.h \
		/opt/Qt/include/QtCore/qchar.h \
		/opt/Qt/include/QtCore/qbytearray.h \
		/opt/Qt/include/QtCore/qrefcount.h \
		/opt/Qt/include/QtCore/qarraydata.h \
		/opt/Qt/include/QtCore/qstringbuilder.h \
		/opt/Qt/include/QtCore/qlist.h \
		/opt/Qt/include/QtCore/qalgorithms.h \
		/opt/Qt/include/QtCore/qiterator.h \
		/opt/Qt/include/QtCore/qhashfunctions.h \
		/opt/Qt/include/QtCore/qpair.h \
		/opt/Qt/include/QtCore/qbytearraylist.h \
		/opt/Qt/include/QtCore/qstringlist.h \
		/opt/Qt/include/QtCore/qregexp.h \
		/opt/Qt/include/QtCore/qstringmatcher.h \
		/opt/Qt/include/QtCore/qcoreevent.h \
		/opt/Qt/include/QtCore/qscopedpointer.h \
		/opt/Qt/include/QtCore/qmetatype.h \
		/opt/Qt/include/QtCore/qvarlengtharray.h \
		/opt/Qt/include/QtCore/qcontainerfwd.h \
		/opt/Qt/include/QtCore/qobject_impl.h \
		/opt/Qt/include/QtCore/qmargins.h \
		/opt/Qt/include/QtGui/qpaintdevice.h \
		/opt/Qt/include/QtCore/qrect.h \
		/opt/Qt/include/QtCore/qsize.h \
		/opt/Qt/include/QtCore/qpoint.h \
		/opt/Qt/include/QtGui/qpalette.h \
		/opt/Qt/include/QtGui/qcolor.h \
		/opt/Qt/include/QtGui/qrgb.h \
		/opt/Qt/include/QtGui/qrgba64.h \
		/opt/Qt/include/QtGui/qbrush.h \
		/opt/Qt/include/QtCore/qvector.h \
		/opt/Qt/include/QtGui/qmatrix.h \
		/opt/Qt/include/QtGui/qpolygon.h \
		/opt/Qt/include/QtGui/qregion.h \
		/opt/Qt/include/QtCore/qdatastream.h \
		/opt/Qt/include/QtCore/qiodevice.h \
		/opt/Qt/include/QtCore/qline.h \
		/opt/Qt/include/QtGui/qtransform.h \
		/opt/Qt/include/QtGui/qpainterpath.h \
		/opt/Qt/include/QtGui/qimage.h \
		/opt/Qt/include/QtGui/qpixelformat.h \
		/opt/Qt/include/QtGui/qpixmap.h \
		/opt/Qt/include/QtCore/qsharedpointer.h \
		/opt/Qt/include/QtCore/qshareddata.h \
		/opt/Qt/include/QtCore/qhash.h \
		/opt/Qt/include/QtCore/qsharedpointer_impl.h \
		/opt/Qt/include/QtGui/qfont.h \
		/opt/Qt/include/QtGui/qfontmetrics.h \
		/opt/Qt/include/QtGui/qfontinfo.h \
		/opt/Qt/include/QtWidgets/qsizepolicy.h \
		/opt/Qt/include/QtGui/qcursor.h \
		/opt/Qt/include/QtGui/qkeysequence.h \
		/opt/Qt/include/QtGui/qevent.h \
		/opt/Qt/include/QtCore/qvariant.h \
		/opt/Qt/include/QtCore/qmap.h \
		/opt/Qt/include/QtCore/qdebug.h \
		/opt/Qt/include/QtCore/qtextstream.h \
		/opt/Qt/include/QtCore/qlocale.h \
		/opt/Qt/include/QtCore/qset.h \
		/opt/Qt/include/QtCore/qcontiguouscache.h \
		/opt/Qt/include/QtCore/qurl.h \
		/opt/Qt/include/QtCore/qurlquery.h \
		/opt/Qt/include/QtCore/qfile.h \
		/opt/Qt/include/QtCore/qfiledevice.h \
		/opt/Qt/include/QtGui/qvector2d.h \
		/opt/Qt/include/QtGui/qtouchdevice.h \
		ui_MainDialog.h \
		MorgageCalculator.h \
		/opt/Qt/include/QtWidgets/QWidget \
		/opt/Qt/include/QtCore/QString
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainDialog.o MainDialog.cpp

moc_MorgageCalculator.o: moc_MorgageCalculator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MorgageCalculator.o moc_MorgageCalculator.cpp

moc_MainDialog.o: moc_MainDialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainDialog.o moc_MainDialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

